# Site settings
name: 侯春宇
location: 北京
company: 天创信用服务有限公司
position: Java开发工程师
github: https://github.com/houcy7
#facebook: https://www.facebook.com/
phone: 15774313113
email: houcy7@163.com


baseurl: "/"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

